// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8YzAmmUGW38sVoS_Xykj8Et10ubJV76Y',
    appId: '1:448356797242:web:e12e577c5d9f20820a9e03',
    messagingSenderId: '448356797242',
    projectId: 'iotirr',
    authDomain: 'iotirr.firebaseapp.com',
    databaseURL: 'https://iotirr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotirr.appspot.com',
    measurementId: 'G-356YGDH0QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4xPMtjlOCN-4RIV1zsVXGCUUHTV3UWNE',
    appId: '1:448356797242:android:4cb6ae8d7ee8cc120a9e03',
    messagingSenderId: '448356797242',
    projectId: 'iotirr',
    databaseURL: 'https://iotirr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotirr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA74ni2MhiYq28Fo9nXc8pIJNYL7os53iE',
    appId: '1:448356797242:ios:b562ddece0c661eb0a9e03',
    messagingSenderId: '448356797242',
    projectId: 'iotirr',
    databaseURL: 'https://iotirr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotirr.appspot.com',
    iosBundleId: 'com.example.iotirr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA74ni2MhiYq28Fo9nXc8pIJNYL7os53iE',
    appId: '1:448356797242:ios:265976bd735d71ea0a9e03',
    messagingSenderId: '448356797242',
    projectId: 'iotirr',
    databaseURL: 'https://iotirr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotirr.appspot.com',
    iosBundleId: 'com.example.iotirr.RunnerTests',
  );
}
